// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSProject1.Data;

#nullable disable

namespace SSProject1.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20220818162908_AddBookings")]
    partial class AddBookings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SSProject1.Models.Booking", b =>
                {
                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.HasKey("FlightId", "PassengerId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("SSProject1.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArrivalDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BookingFlightId")
                        .HasColumnType("int");

                    b.Property<int?>("BookingPassengerId")
                        .HasColumnType("int");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingFlightId", "BookingPassengerId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("SSProject1.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("BookingFlightId")
                        .HasColumnType("int");

                    b.Property<int?>("BookingPassengerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingFlightId", "BookingPassengerId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("SSProject1.Models.Booking", b =>
                {
                    b.HasOne("SSProject1.Models.Flight", "Flight")
                        .WithMany("BookedPassengers")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SSProject1.Models.Passenger", "Passenger")
                        .WithMany("BookedFlights")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("SSProject1.Models.Flight", b =>
                {
                    b.HasOne("SSProject1.Models.Booking", null)
                        .WithMany("Flights")
                        .HasForeignKey("BookingFlightId", "BookingPassengerId");
                });

            modelBuilder.Entity("SSProject1.Models.Passenger", b =>
                {
                    b.HasOne("SSProject1.Models.Booking", null)
                        .WithMany("Passengers")
                        .HasForeignKey("BookingFlightId", "BookingPassengerId");
                });

            modelBuilder.Entity("SSProject1.Models.Booking", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("SSProject1.Models.Flight", b =>
                {
                    b.Navigation("BookedPassengers");
                });

            modelBuilder.Entity("SSProject1.Models.Passenger", b =>
                {
                    b.Navigation("BookedFlights");
                });
#pragma warning restore 612, 618
        }
    }
}
